spring:
  datasource:
    url: jdbc:mysql://brad0321.c9y26kamyq64.ap-southeast-2.rds.amazonaws.com:3306/brad?sslMode=REQUIRED&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: brad0321
    password: totty8302##     # ← 비번은 곧 바꾸는 걸 권장
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          # ★ RDS 데이터 보호 (create/update 금지)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: true

logging:
  level:
    org.thymeleaf: DEBUG
    org.springframework.web: DEBUG