spring:
  datasource:
    url: jdbc:mysql://brad0321.c9y26kamyq64.ap-southeast-2.rds.amazonaws.com:3306/brad
    username: brad0321
    password: totty8302##
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate.format_sql: true

  thymeleaf:
    cache: false
    # 템플릿을 클래스패스가 아닌 실제 파일 경로에서 바로 읽도록 (수정 즉시 반영)
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false


server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always